export const tableConfigs = [
  {
    id: 'patients',
    label: 'Patients',
    table: 'Patient',
    primaryKey: 'patient_id',
    defaultOrderBy: 'patient_id',
    description: 'Patient demographics, contact information, and visit details.',
    fields: [
      { name: 'patient_id', label: 'Patient ID', inForm: false, inTable: true },
      { name: 'first_name', label: 'First name', type: 'text', required: true },
      { name: 'last_name', label: 'Last name', type: 'text', required: true },
      { name: 'date_of_birth', label: 'Date of birth', type: 'date' },
      { name: 'phone_number', label: 'Phone number', type: 'number' },
      { name: 'street_number', label: 'Street number', type: 'number' },
      { name: 'street_name', label: 'Street name', type: 'text' },
      { name: 'city', label: 'City', type: 'text' },
      { name: 'country', label: 'Country', type: 'text' },
      { name: 'postal_code', label: 'Postal code', type: 'text' },
      { name: 'time_in', label: 'Time in', type: 'time' },
      { name: 'time_out', label: 'Time out', type: 'time' },
      { name: 'insurance_info', label: 'Insurance info', type: 'textarea' },
      { name: 'patient_history', label: 'Patient history', type: 'textarea' },
    ],
  },
  {
    id: 'appointments',
    label: 'Appointments',
    table: 'appointments',
    primaryKey: 'id',
    defaultOrderBy: 'start_time',
    description: 'Scheduled visits between patients and providers.',
    fields: [
      { name: 'id', label: 'ID', inForm: false, inTable: true },
      { name: 'patient_id', label: 'Patient ID', type: 'text', required: true },
      { name: 'provider_name', label: 'Provider', type: 'text' },
      { name: 'start_time', label: 'Start time', type: 'datetime-local', required: true },
      { name: 'end_time', label: 'End time', type: 'datetime-local' },
      {
        name: 'status',
        label: 'Status',
        type: 'select',
        options: ['scheduled', 'checked_in', 'completed', 'cancelled', 'no_show'],
      },
      { name: 'reason', label: 'Reason for visit', type: 'textarea' },
    ],
  },
  {
    id: 'diagnoses',
    label: 'Diagnoses',
    table: 'diagnoses',
    primaryKey: 'id',
    defaultOrderBy: 'recorded_at',
    description: 'Clinical diagnoses associated with encounters.',
    fields: [
      { name: 'id', label: 'ID', inForm: false, inTable: true },
      { name: 'patient_id', label: 'Patient ID', type: 'text', required: true },
      { name: 'appointment_id', label: 'Appointment ID', type: 'text' },
      { name: 'code', label: 'Code (e.g. ICD-10)', type: 'text', required: true },
      { name: 'description', label: 'Description', type: 'textarea', required: true },
      { name: 'recorded_at', label: 'Recorded at', type: 'datetime-local' },
    ],
  },
  {
    id: 'prescriptions',
    label: 'Prescriptions',
    table: 'prescriptions',
    primaryKey: 'id',
    defaultOrderBy: 'start_date',
    description: 'Medication prescriptions for patients.',
    fields: [
      { name: 'id', label: 'ID', inForm: false, inTable: true },
      { name: 'patient_id', label: 'Patient ID', type: 'text', required: true },
      { name: 'drug_id', label: 'Drug ID', type: 'text', required: true },
      { name: 'dosage', label: 'Dosage', type: 'text', required: true },
      { name: 'frequency', label: 'Frequency', type: 'text', required: true },
      { name: 'route', label: 'Route', type: 'text' },
      { name: 'start_date', label: 'Start date', type: 'date' },
      { name: 'end_date', label: 'End date', type: 'date' },
      { name: 'instructions', label: 'Instructions', type: 'textarea' },
    ],
  },
  {
    id: 'drugs',
    label: 'Drugs',
    table: 'drugs',
    primaryKey: 'id',
    defaultOrderBy: 'name',
    description: 'Reference table of medications.',
    fields: [
      { name: 'id', label: 'ID', inForm: false, inTable: true },
      { name: 'name', label: 'Brand name', type: 'text', required: true },
      { name: 'generic_name', label: 'Generic name', type: 'text' },
      { name: 'strength', label: 'Strength', type: 'text' },
      { name: 'form', label: 'Form (tablet, capsule, etc.)', type: 'text' },
      { name: 'manufacturer', label: 'Manufacturer', type: 'text' },
    ],
  },
  {
    id: 'billings',
    label: 'Billing',
    table: 'billing',
    primaryKey: 'id',
    defaultOrderBy: 'created_at',
    description: 'Billing records for visits and services.',
    fields: [
      { name: 'id', label: 'ID', inForm: false, inTable: true },
      { name: 'patient_id', label: 'Patient ID', type: 'text', required: true },
      { name: 'appointment_id', label: 'Appointment ID', type: 'text' },
      { name: 'amount', label: 'Amount', type: 'number', required: true },
      {
        name: 'status',
        label: 'Status',
        type: 'select',
        options: ['pending', 'submitted', 'paid', 'denied', 'written_off'],
      },
      { name: 'due_date', label: 'Due date', type: 'date' },
      { name: 'paid_at', label: 'Paid at', type: 'datetime-local' },
    ],
  },
  {
    id: 'invoices',
    label: 'Invoices',
    table: 'invoices',
    primaryKey: 'id',
    defaultOrderBy: 'issued_date',
    description: 'Patient-facing invoices derived from billing.',
    fields: [
      { name: 'id', label: 'ID', inForm: false, inTable: true },
      { name: 'patient_id', label: 'Patient ID', type: 'text', required: true },
      { name: 'billing_id', label: 'Billing ID', type: 'text' },
      { name: 'invoice_number', label: 'Invoice number', type: 'text', required: true },
      { name: 'total_amount', label: 'Total amount', type: 'number', required: true },
      {
        name: 'status',
        label: 'Status',
        type: 'select',
        options: ['draft', 'sent', 'paid', 'void'],
      },
      { name: 'issued_date', label: 'Issued date', type: 'date' },
      { name: 'due_date', label: 'Due date', type: 'date' },
    ],
  },
  {
    id: 'lab_orders',
    label: 'Lab Orders',
    table: 'lab_orders',
    primaryKey: 'id',
    defaultOrderBy: 'ordered_at',
    description: 'Orders for diagnostic lab tests.',
    fields: [
      { name: 'id', label: 'ID', inForm: false, inTable: true },
      { name: 'patient_id', label: 'Patient ID', type: 'text', required: true },
      { name: 'appointment_id', label: 'Appointment ID', type: 'text' },
      { name: 'test_name', label: 'Test name', type: 'text', required: true },
      {
        name: 'priority',
        label: 'Priority',
        type: 'select',
        options: ['routine', 'urgent', 'stat'],
      },
      {
        name: 'status',
        label: 'Status',
        type: 'select',
        options: ['ordered', 'in_progress', 'completed', 'cancelled'],
      },
      { name: 'ordered_at', label: 'Ordered at', type: 'datetime-local' },
    ],
  },
  {
    id: 'lab_results',
    label: 'Lab Results',
    table: 'lab_results',
    primaryKey: 'id',
    defaultOrderBy: 'reported_at',
    description: 'Results received for lab orders.',
    fields: [
      { name: 'id', label: 'ID', inForm: false, inTable: true },
      { name: 'lab_order_id', label: 'Lab order ID', type: 'text', required: true },
      { name: 'result_value', label: 'Result value', type: 'text', required: true },
      { name: 'unit', label: 'Unit', type: 'text' },
      { name: 'reference_range', label: 'Reference range', type: 'text' },
      {
        name: 'status',
        label: 'Status',
        type: 'select',
        options: ['normal', 'abnormal', 'critical', 'pending'],
      },
      { name: 'reported_at', label: 'Reported at', type: 'datetime-local' },
    ],
  },
  {
    id: 'coverage',
    label: 'Coverage',
    table: 'coverage',
    primaryKey: 'id',
    defaultOrderBy: 'coverage_start',
    description: 'Insurance coverage details for patients.',
    fields: [
      { name: 'id', label: 'ID', inForm: false, inTable: true },
      { name: 'patient_id', label: 'Patient ID', type: 'text', required: true },
      { name: 'provider_name', label: 'Insurance provider', type: 'text', required: true },
      { name: 'plan_name', label: 'Plan name', type: 'text' },
      { name: 'member_id', label: 'Member ID', type: 'text' },
      { name: 'coverage_start', label: 'Coverage start', type: 'date' },
      { name: 'coverage_end', label: 'Coverage end', type: 'date' },
    ],
  },
];
